server:
  port: 8443
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/my_white_jotter?useUnicode=true&characeterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      schema-locations: classpath*:sql/init.sql
      data-locations: classpath*:sql/data.sql
      mode: never
debug: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml

